spring:
  application:
    name: SEP490-G2-FA24
  main:
    allow-bean-definition-overriding: true
  datasource:
    url:
    hikari:
      minimum-idle: 5
      idleTimeout: 30000
      pool-name: HikariCP
      maximum-pool-size: 20
      max-lifetime: 2000000
      connection-timeout: 30000
      username:
      password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle12cDialect
      open-in-view: false
    lifecycle:
      timeout-per-shutdown-phase: 30s
server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: none
logging:
  level:
    org.springframework.security: TRACE




