cors:
  allowed-origins: "*"
  allowed-methods: "*"
spring:
  application:
    name: NihonGo-Admin
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/nihongo
    username: root
    password: 1234
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mail:
    host: smtp.gmail.com
    port: 587
    username: btung548@gmail.com
    password: wtpl thuu nomh hvua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182534795296-7pu8qv2kdlmjfql8ujer899djgjq2s7b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org.springframework.security: TRACE
server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: none


